### ISSUE TITLE
Add "Code generated ..." comment line automatically

### ISSUE THREAD

**Issue by kohenkatz** [droyo/go-xml#105]
The documentation for `go generate` says this:

>To convey to humans and machine tools that code is generated,
generated source should have a line that matches the following
regular expression (in Go syntax):
>
>     ^// Code generated .* DO NOT EDIT\.$
>
>The line may appear anywhere in the file, but is typically
placed near the beginning so it is easy to find.

Many static analysis tools for Go will treat a file differently if they see that it has been machine-generated. For example, go-lint will ignore files with this comment.

It would be nice if these tools would add a line like this automatically. I know it can be done using the `-c` argument, but I can't think of any reason not to always have it there.

I'd be happy to open a PR if you want.

**Comment by droyo** [comment]
Thanks for reaching out. I'd be happy to accept a PR with this change!
