### ISSUE TITLE
could not find base type anySimpleType in namespace http://www.w3.org/2001/XMLSchema

### ISSUE THREAD

**Issue by remiphilippe** [droyo/go-xml#117]
Hello,
I'm trying to generate the schema for STIX 1.2 (https://github.com/STIXProject/schemas), but any schema I try (tried cybox common and common that both have anySimpletype) always fails with the error:
```
> xsdgen -vv common.xsd # Note common is this file: https://github.com/STIXProject/schemas/blob/master/common.xsd
read common.xsd
setting namespaces to ["http://docs.oasis-open.org/cti/ns/stix/common-1"]
complexType ControlledVocabularyStringType: could not find base type anySimpleType in namespace http://www.w3.org/2001/XMLSchema
```

I do see this defined in the builtins but it doesn't seem to be picked up (pretty close to this one: https://github.com/droyo/go-xml/issues/112, but not the same error). Is there an XSD I should be passing despite the builtin?

Thanks!

**Comment by remiphilippe** [comment]
After a bit more research, looks like `anySimpleType` was introduced with XSD 1.1 (https://www.liquid-technologies.com/Reference/XmlStudio/XsdEditorNotation_BuiltInXsdTypes.html), but XML file is defined with `<?xml version="1.0" encoding="UTF-8"?>`, not sure if that's something which is "legit"

**Comment by StabbyCutyou** [comment]
Not sure what kind of usable code it outputs, but changing this line https://github.com/droyo/go-xml/blob/master/xsd/builtin.go#L96 to "AnySimpleType" prevents this error.

**Comment by droyo** [comment]
@StabbyCutyou found the bug, it was an oversight in https://github.com/droyo/go-xml/commit/d7de88e1dfd94ebd3b0562f49285b7809286a360

I've made the suggested change, @remiphilippe how does it look now?
