### ISSUE TITLE
complexType DetailedHashSum: could not find type "BinaryDataType" in namespace http://service.ddex.net/xml/avs/avs for element DataType

### ISSUE THREAD

**Issue by imxyb** [droyo/go-xml#123]
i use your xsdgen to parse the ddex xsd, but occur this error, can you help me to solve it?

the xsd link: http://service.ddex.net/xml/ern/41/release-notification.xsd

thanks.

**Comment by imxyb** [comment]
cmd:
```
xsdgen -vv ~/Desktop/release-notification.xsd ~/Desktop/avs.xsd
read /Users/imxyb/Desktop/release-notification.xsd
read /Users/imxyb/Desktop/avs.xsd
setting namespaces to ["http://ddex.net/xml/ern/41" "http://ddex.net/xml/avs/avs"]
complexType Video: could not find type "CompositeMusicalWorkType" in namespace http://ddex.net/xml/avs/avs for element CompositeMusicalWorkType
```

**Comment by droyo** [comment]
I'm not sure you got the right `avs.xsd`. The schema you shared has 

	<xs:import namespace="http://ddex.net/xml/avs/avs" schemaLocation="http://ddex.net/xml/avs/avs4.xsd"/>

Which contains the `CompositeMusicalWorkType` definition. I downloaded http://ddex.net/xml/avs/avs4.xsd and ran your command and it generated output that looks OK (https://gist.github.com/droyo/a1da9e8318270a5d1a14155d92be64f3). Here's the code for the type mentioned in the error:

	// May be one of Medley, Neither, Potpourri
	type CompositeMusicalWorkType string

**Comment by droyo** [comment]
Please re-open if you still have an issue
