### ISSUE TITLE
complexType localElement: could not find type  in namespace  for attribute substitutionGroup

### ISSUE THREAD

**Issue by danielvladco** [droyo/go-xml#125]
I was trying to generate go structure for xsl Transform (http://www.w3.org/1999/XSL/Transform)

After running: `xsdgen xslt.xsd XMLSchema.xsd hfp.xsd`
## expected result
generated go types

## actual result
error
`complexType localElement: could not find type  in namespace  for attribute substitutionGroup`

## additional info
When looking in XMLSchema (http://www.w3.org/2001/XMLSchema)
```xml
<xs:attribute name="substitutionGroup" use="prohibited"/>
<xs:attribute name="final" use="prohibited"/>
<xs:attribute name="abstract" use="prohibited"/>
```
the problem is that some attributes are missing types and have `use="prohibited"` option
is it possible to somehow omit these attributes or assign `interface{}`

**Comment by droyo** [comment]
According to the spec:

"If the <attribute> element information item has use='prohibited', then it does not map to, or correspond to, any schema component at all."

I wonder why `prohibited` even exists. I suppose there could be some use case where you'd want to fail validation of a document that uses a prohibited attribute. This package does not attempt to be a validator, so I wonder if we could disregard these attributes entirely. Although if we do that, we'd run the risk of other elements referencing those attributes which we've conveniently ignored. I guess that is what your error is showing.

Should the type of these attributes be something like an `interface{}`, allowing anything, or something like a `struct{}`, allowing nothing?

**Comment by danielvladco** [comment]
I agree, we shouldn't disregard these attributes entirely, I think the best way of approaching this is to assign `interface{}` type. However I am not an xml expert, I just want to generate my go code =) So any solution will be fine for me.

**Comment by droyo** [comment]
Can you let me know if the PR in #126 resolves the issue? Thanks!

**Comment by danielvladco** [comment]
it solves the issue for use="prohibited". However now I get the same error for other attributes. For example:
```
complexType facet: could not find type  in namespace  for attribute value
```
the attribute:
```xml
<xs:attribute name="value" use="required"/>
```
Can this be because on an older xsd format that allows not specifying the attribute type?

This is the file that generates errors: https://www.w3.org/2001/XMLSchema

**Comment by droyo** [comment]
Ok, looking closer at [the spec](https://www.w3.org/TR/xmlschema-1/#declare-attribute):

> {type definition}: The simple type definition corresponding to the <simpleType> element information item in the [children], if present, otherwise the simple type definition ·resolved· to by the ·actual value· of the type [attribute], if present, otherwise the ·simple ur-type definition·.

If I read that right, it's saying attributes default to `anySimpleType`. I pushed an update to #126 that does this, let me know if it works. I wonder if we need something similar for elements defaulting to `anyType`.

**Comment by danielvladco** [comment]
Now that it does not throw any error but it takes forever to execute. Might be because of recursive access. 

Now that I think about it, I probably shouldn't have included https://www.w3.org/2001/XMLSchema file. This is supposed to be the schema for built-in types right?

If I don't include that file it does not execute forever but I get:
```
gen type "fallback": fallback attribute space: Unknown built-in type "anySimpleType"
```

**Comment by droyo** [comment]
https://www.w3.org/2001/XMLSchema is already bundled with the `xsd` package in `standard-schema.go` and does not need to be specified on the command line.

I've pushed another commit addressing your latest error, let me know how it goes.

**Comment by danielvladco** [comment]
```
gen type "element-names": don't know how to marshal/unmarshal <list> of AnySimpleType
gen type "QNames": don't know how to marshal/unmarshal <list> of AnySimpleType
exit status 1
```
This is the file
[xslt.txt](https://github.com/droyo/go-xml/files/5612864/xslt.txt)

**Comment by droyo** [comment]
Fixed that, here's the output: https://gist.github.com/droyo/1d566c109d86fb34e79244bf27f7cbfe

**Comment by danielvladco** [comment]
Cool, works amazing, thanks for fast reply and fix

**Comment by droyo** [comment]
OK, I'll go ahead and merge it. Looking at the output it reminds me that #2 is still open.
