### ISSUE TITLE
question about walking the xsd

### ISSUE THREAD

**Issue by jmccormick2001** [droyo/go-xml#133]
Hi, I would like to see if you have an example of walking the xsd after it is read in.  I'd like to write some code that uses the parsed xsd.

Is there a good example you could share that does that?

many thanks.

**Comment by jmccormick2001** [comment]
what I'm wanting to do is generate xmlpath based on the xsd, not sure if you know of some code that already does that.

**Comment by droyo** [comment]
I would use the `xmltree` package to walk the xsd. It provides a recursive data structure that you can walk with a recursive function (or iteratively, if you need to walk really deep trees). Something like this would print out "breadcrumbs" for each element;

	func join(prefix, name string) string {
		if prefix == "" {
			return name
		}
		return prefix + "." + name
	}
	func walk(prefix string, el *xmltree.Element) {
		scope := join(prefix, el.Name.Local)
		println(scope)
		for _, c := range el.Children {
			walk(scope, &c)
		}
	}
	func main() {
		doc, _ := xmltree.Parse([]byte("<foo><bar><baz></baz></bar></foo>"))
		walk("", doc)
	}

**Comment by jmccormick2001** [comment]
ah, perfect, many thanks, great work on this repo/package!
