### ISSUE TITLE
nil base type causes panic in xsdgen/xsdgen.go Config.flatten1()

### ISSUE THREAD

**Issue by onitake** [droyo/go-xml#16]
When a SimpleType without a base type is processed in flatten1(), the debugf() on line xsdgen/xsdgen.go:280 causes xsdgen to crash - calling XMLName(nil) will trigger the panic() in xsd/xsd.go:293.

Since this is only used for debugging, it's probably a good idea to remove the panic() completely or guard this with a check:
```
		if builtin == nil {
			cfg.debugf("%T(%s) has no base type, cannot transform", t, xsd.XMLName(t).Local)
		} else {
			cfg.debugf("Transforming %T(%s) into base type %T(%s)", t, xsd.XMLName(t).Local, t.Base, xsd.XMLName(t.Base).Local)
		}
```
And before returning t.Base (which is nil), there should be something like this:
```
		if t.Base == nil {
			return t
		}
```

I don't really understand why there is no base type in my particular test case, but handling this special case may be a good idea anyway?

For reference, this is the XSD I'm trying to process:
http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd
And the type that it hits is a ConditionalUintType.

**Comment by droyo** [comment]
Thanks for providing the xsd. I'm surprised the type had no Base, that points to a possible error in the xsd package or some of the transformations done in xsdgen.

**Comment by droyo** [comment]
Looked into this further, I think the issue is that ConditionalUintType is a Union, and doesn't have a Base. So, while it calls into question my decision to make `Union` a separate member of `xsd.SimpleType`, this isn't an error in the `xsd` package and adding the guard seems like the most sensible thing to do.
