### ISSUE TITLE
xsdgen: "could not find ref ds:Signature in ..."

### ISSUE THREAD

**Issue by andreynering** [droyo/go-xml#37]
Hi,

I just tried the generator and it gives me this error. I'm not sure if it's a bug or I'm missing something.

```sh
$ xsdgen -pkg=types -o=types/evtAdmPrelim.go xsd/evtAdmPrelim.xsd
could not find ref ds:Signature in <xs:element ref="ds:Signature" xmlns="http://www.esocial.gov.br/schema/evt/evtAdmPrelim/v02_04_00" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xs="http://www.w3.org/2001/XMLSchema"></xs:element>
```

[evtAdmPrelim.xsd.txt](https://github.com/droyo/go-xml/files/1402016/evtAdmPrelim.xsd.txt)

**Comment by droyo** [comment]
xsdgen does not download dependencies for you. You have to download the XSD for 

	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>

yourself and provide it as another argument on the command line. I think that XSD is at https://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd. For example:

	xsdgen -pkg types -ns http://www.esocial.gov.br/schema/evt/evtAdmPrelim/v02_04_00 -o types/evtAdmPrelim.go xsd/evtAdmPrelim.xsd xsd/xmldsig-core-schema.xsd

Let me know if that works.

**Comment by droyo** [comment]
I went ahead and did this myself. There's a few errors in the generated output:

	./xsdgen_output.go:129:2: duplicate field Items
	./xsdgen_output.go:132:2: duplicate field PGPKeyPacket
	./xsdgen_output.go:141:3: duplicate field PGPKeyPacket
	./xsdgen_output.go:145:8: ambiguous selector layout.PGPKeyPacket
	./xsdgen_output.go:145:48: ambiguous selector layout.T.PGPKeyPacket

It looks to be getting tripped up by complex model groups such as

	<complexType name="PGPDataType"> 
	  <choice>
	    <sequence>
	      <element name="PGPKeyID" type="base64Binary"/> 
	      <element name="PGPKeyPacket" type="base64Binary" minOccurs="0"/> 
	      <any namespace="##other" processContents="lax" minOccurs="0"
	       maxOccurs="unbounded"/>
	    </sequence>
	    <sequence>
	      <element name="PGPKeyPacket" type="base64Binary"/> 
	      <any namespace="##other" processContents="lax" minOccurs="0"
	       maxOccurs="unbounded"/>
	    </sequence>
	  </choice>
	</complexType>

The `xsd` package cuts corners and doesn't consider model groups like `sequence`, `choice`, or `all`. It just flattens all elements and attributes within a `complexContent`.

So a quick fix would be to skip duplicate elts/attributes within a `complexContent`, effectively making the Go type a union of all model groups within the `complexContent`. That is not good enough for an XSD validator, but it should be good enough for a client that needs to marshal/unmarshal documents.

**Comment by droyo** [comment]
I just pushed the fix I described, and I'm able to generate valid Go code. I can't say whether it properly decodes/encodes the target document without some sample data. Give it a try and let me know.

**Comment by andreynering** [comment]
Thanks a lot @droyo, for your help and work.

I'll be able to test this at Monday.

**Comment by andreynering** [comment]
Thanks again @droyo. I was able to make it work.
