### ISSUE TITLE
No Base Set for Empty Complex Types

### ISSUE THREAD

**Issue by ianlopshire** [droyo/go-xml#50]
When a complex type is empty, no base is set. This causes panics and unintended behavior elsewhere in the codebase.

example xml:
```xml
<xsd:complexType name="Get_Committee_Defintion_Request_CriteriaType">
    <xsd:annotation>
        <xsd:documentation>Committee Definition Request Criteria</xsd:documentation>
    </xsd:annotation>
</xsd:complexType>
```

I believe a solution to this issue would be to assign a base of AnyType to empty complex types. @droyo Would you suggest anything else?

**Comment by droyo** [comment]
Such a type should indeed have a base type of AnyType. I'm a bit surprised that this happens, I expected the expandComplexShorthand function to transform the above to a restriction of AnyType. That was certainly the intention, anyway. 

I can get a fix in for this tomorrow. Thanks for reporting it.
