### ISSUE TITLE
xsdgen problem

### ISSUE THREAD

**Issue by junghao** [droyo/go-xml#9]
Hi,

I've used xsdgen command line to generate xsd from http://www.fdsn.org/xml/station/1 .
However, the generated go skipped the base type for xs:restriction.

For example, if you look into the generated go struct of "Longitude"->"LongitudeType"->"LongitudeBaseType" you'll see there's no "FloatType" field:
```
type LatitudeBaseType struct {
	Unit       string  `xml:"unit,attr"`
	PlusError  float64 `xml:"plusError,attr"`
	MinusError float64 `xml:"minusError,attr"`
}
```
, but the xsd of LongitudeBaseType is:
```
<xs:complexType name="LongitudeBaseType">
		<xs:simpleContent>
			<xs:restriction base="fsx:FloatType">
				<xs:minInclusive value="-180"/>
				<xs:maxInclusive value="180"/>
				<xs:attribute name="unit" type="xs:string" use="optional" fixed="DEGREES"/>
				<xs:attributeGroup ref="fsx:uncertaintyDouble"/>
			</xs:restriction>
		</xs:simpleContent>
	</xs:complexType>
```

**Comment by droyo** [comment]
Reading through [the xsd](http://www.fdsn.org/xml/station/fdsn-station-1.0.xsd) file, I see `FloatType` defined as

	<xs:complexType name="FloatType">
	  <xs:annotation>
	    <xs:documentation>
	      Representation of floating-point numbers used as measurements.
	    </xs:documentation>
	  </xs:annotation>
	  <xs:simpleContent>
	    <xs:extension base="xs:double">
	      <xs:attribute name="unit" type="xs:string" use="optional"/>
	      <xs:attributeGroup ref="fsx:uncertaintyDouble"/>
	    </xs:extension>
	  </xs:simpleContent>
	</xs:complexType>

So, at least from my initial reading, the problem is that there is no field for the content between the tags. In this case, we should know that the content should be captured by the use of `<simpleContent>` in the definition of `FloatType`, so I can add a field to the `xsd.SimpleType` and `xsd.ComplexType` types to denote that its content is significant. However, I need to re-read the spec to determine if this covers all cases.

**Comment by droyo** [comment]
I'm actually having some trouble coming up with what the desired type declaration would be. Presumably something like

	type LatitudeBaseType struct {
		Unit       string  `xml:"unit,attr"`
		PlusError  float64 `xml:"plusError,attr"`
		MinusError float64 `xml:"minusError,attr"`
		Value float64
	}

The problem I'm having is getting the right struct tag for the `encoding/xml` package to unmarshal the content into the `Value` field. Here's a simplified example: https://play.golang.org/p/1fhvkNSDxu

**Comment by droyo** [comment]
It looks like this will work:

	type LatitudeBaseType struct {
		Unit       string  `xml:"unit,attr"`
		PlusError  float64 `xml:"plusError,attr"`
		MinusError float64 `xml:"minusError,attr"`
		Value float64 `xml:",chardata"`
	}

**Comment by droyo** [comment]
To answer my previous question, a complex type should capture character data when its content is made of `simpleContent` or `complexContent` with `mixed=true`.

**Comment by droyo** [comment]
OK, actually reading the code, it appears that I was already handling a similar case, [here](https://github.com/droyo/go-xml/blob/22da4247c58575a85605a907b8cdf96de404f843/xsdgen/xsdgen.go#L403-L418), where the chardata field is added if a complex type extended a simple type. However, it did not catch the case where a complex type *restricted* a complex type that *extended* a simple type. I'm getting dizzy...

**Comment by droyo** [comment]
Hi @junghao , thanks for your patience. PR #10 should have fixed this issue. Here's a snippet of the code generated from your xsd:

	// Base latitude type. Because of the limitations of schema, defining
	// this type and then extending it to create the real latitude type is the only way to
	// restrict values while adding datum as an attribute.
	type LatitudeBaseType struct {
		Value      float64 `xml:",chardata"`
		Unit       string  `xml:"unit,attr"`
		PlusError  float64 `xml:"plusError,attr"`
		MinusError float64 `xml:"minusError,attr"`
	}

Let me know if that works for you.

**Comment by junghao** [comment]
Cool, it's been fixed.
