### ISSUE TITLE
Expired certificate for aqwari.net

### ISSUE THREAD

**Issue by bmatthews** [droyo/go-xml#97]
The certificate for aqwari.net expired Thursday, 30 January 2020 at 13:42:38 this causes the following failure on go get. (https fetch: Get https://aqwari.net/xml?go-get=1: x509: certificate has expired or is not yet valid

**Comment by droyo** [comment]
Sorry about this. I replaced the cert on Feb 4th. My letsencrypt auto-renewal was not working correctly.
